# -*- coding: utf-8 -*-
"""apec_scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vg3y4Utma1TG7TkM-TftaZSOjdmQ_RUf
"""

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import StaleElementReferenceException
import time

driver.get('page_link')
accept_btn = driver.find_element(By.ID, 'onetrust-accept-btn-handler')
accept_btn.click()
login_input = driver.find_element(By.NAME, 'emailid')
login_input.send_keys("email@email.com")
password_input = driver.find_element(By.NAME, 'password')
password_input.send_keys("password")
submit_button = driver.find_element(By.XPATH,"//button[@class='popin-btn-primary' and @type='submit' and contains(text(),'Se connecter')]")
submit_button.click()

i=0
while i<10:
    index = 0
    elements = driver.find_elements(By.CLASS_NAME, 'actualLink')
    while index < len(elements):
        element = elements[index]
        element.click()
        time.sleep(2)
        dropdown_toggle = driver.find_element(By.CLASS_NAME, 'dropdown-toggle')
        dropdown_toggle.click()
        time.sleep(1)
        try:
            option = driver.find_element(By.XPATH, '//a[contains(@href,"filename=Profil et CV")]')
            option.click()
        except StaleElementReferenceException:
            pass
        driver.back()
        time.sleep(3)
        index += 1
        elements = driver.find_elements(By.CLASS_NAME, 'actualLink')
    next_button = driver.find_element(By.LINK_TEXT, "Suiv.")
    next_button.click()
    time.sleep(2)
    i+=1